name: Build iOS Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://githubusercontent.com)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Compile Dylib
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 TARGET=iphone:clang:latest:14.0
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Menu-Dylib
          path: "**/obj/*.dylib"
